steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/stella-web:$COMMIT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/stella-web:latest",
        ".",
      ]

  # Push the Docker image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/stella-web:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/stella-web:latest"]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: [
        "run",
        "deploy",
        "stella-web",
        "--image",
        "gcr.io/$PROJECT_ID/stella-web:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--memory",
        "1Gi",
        "--cpu",
        "1",
        "--max-instances",
        "10",
        "--set-env-vars",
        "NODE_ENV=production",
        # Server-side only environment variables (not exposed to client)
        "--set-env-vars",
        "STELLA_APP_HOST=$_STELLA_APP_HOST",
        "--set-env-vars",
        "FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID",
        "--set-env-vars",
        "FIREBASE_CLIENT_EMAIL=$_FIREBASE_CLIENT_EMAIL",
        "--set-env-vars",
        "FIREBASE_PRIVATE_KEY=$_FIREBASE_PRIVATE_KEY",
        # Client-side safe variables (these get built into the app)
        "--set-env-vars",
        "NEXT_PUBLIC_STORJ_PUBLIC_URL=$_STORJ_PUBLIC_URL",
        "--set-env-vars",
        "NEXT_PUBLIC_FIREBASE_API_KEY=$_FIREBASE_API_KEY",
        "--set-env-vars",
        "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$_FIREBASE_AUTH_DOMAIN",
        "--set-env-vars",
        "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID_PUBLIC",
        "--set-env-vars",
        "NEXT_PUBLIC_STELLA_REACT_NATIVE_FOR_WEB_HOST=$_REACT_NATIVE_HOST",
      ]

substitutions:
  # 🔒 Server-side only variables (NEVER expose these publicly)
  _STELLA_APP_HOST: "https://your-backend-api.com"
  _FIREBASE_PROJECT_ID: "your-firebase-project-id"
  _FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-xxxxx@your-project.iam.gserviceaccount.com"
  _FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nYour private key here\n-----END PRIVATE KEY-----"

  # 🌐 Client-side safe variables (these are meant to be public)
  _STORJ_PUBLIC_URL: "https://link.storjshare.io/your-bucket"
  _FIREBASE_API_KEY: "AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  _FIREBASE_AUTH_DOMAIN: "your-project.firebaseapp.com"
  _FIREBASE_PROJECT_ID_PUBLIC: "your-firebase-project-id"
  _REACT_NATIVE_HOST: "https://your-app-domain.com"

images:
  - "gcr.io/$PROJECT_ID/stella-web:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/stella-web:latest"

options:
  logging: CLOUD_LOGGING_ONLY
